// <auto-generated>
// 
//
// Generated by <a href="http://enunciate.codehaus.org">Enunciate</a>.
// </auto-generated>
using System;

namespace Fm.Setlist.Api.Model {

  /// <remarks>
  ///  This class represents an artist. An artist is a musician or a group of
  ///  musicians. Each artist has a definite &lt;a
  ///  href=&quot;http://wiki.musicbrainz.org/MBID&quot;&gt;Musicbrainz Identifier&lt;/a&gt; (MBID)
  ///  with which the artist can be uniquely identified.
  /// </remarks>
  /// <summary>
  ///  This class represents an artist. An artist is a musician or a group of
  ///  musicians. Each artist has a definite &lt;a
  ///  href=&quot;http://wiki.musicbrainz.org/MBID&quot;&gt;Musicbrainz Identifier&lt;/a&gt; (MBID)
  ///  with which the artist can be uniquely identified.
  /// </summary>
  [System.SerializableAttribute()]
  [System.Xml.Serialization.XmlTypeAttribute(Namespace="",TypeName="artist")]
  [System.Xml.Serialization.SoapTypeAttribute(TypeName="artist")]
  [System.Xml.Serialization.XmlRootAttribute(Namespace="",ElementName="artist")]
  public partial class Artist {

    private string _disambiguation;
    private string _mbid;
    private int? _tmid;
    private bool _tmidSpecified;
    private string _name;
    private string _sortName;
    private string _url;
    /// <summary>
    ///  disambiguation to distinguish between artists with same names
    /// </summary>
    [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="disambiguation")]
    [System.Xml.Serialization.SoapAttributeAttribute(AttributeName="disambiguation")]
    public string Disambiguation {
      get {
        return this._disambiguation;
      }
      set {
        this._disambiguation = value;
      }
    }
    /// <summary>
    ///  unique Musicbrainz Identifier (MBID), e.g.
    ///  &lt;em&gt;&amp;quot;b10bbbfc-cf9e-42e0-be17-e2c3e1d2600d&amp;quot;&lt;/em&gt;
    /// </summary>
    [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="mbid")]
    [System.Xml.Serialization.SoapAttributeAttribute(AttributeName="mbid")]
    public string Mbid {
      get {
        return this._mbid;
      }
      set {
        this._mbid = value;
      }
    }
    /// <summary>
    ///  unique Ticket Master Identifier (TMID), e.g. &lt;em&gt;1953&lt;/em&gt;
    /// </summary>
    [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="tmid")]
    [System.Xml.Serialization.SoapAttributeAttribute(AttributeName="tmid")]
    public int Tmid {
      get {
        return this._tmid.GetValueOrDefault();
      }
      set {
        this._tmid = value;
        this._tmidSpecified = true;
      }
    }

    /// <summary>
    ///  Property for the XML serializer indicating whether the "Tmid" property should be included in the output.
    /// </summary>
    [System.Xml.Serialization.XmlIgnoreAttribute]
    [System.Xml.Serialization.SoapIgnoreAttribute]
    [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
    public bool TmidSpecified {
      get {
        return this._tmidSpecified;
      }
      set {
        this._tmidSpecified = value;
      }
    }

    /// <summary>
    ///  the artist's name, e.g. &lt;em&gt;&amp;quot;The Beatles&amp;quot;&lt;/em&gt;
    /// </summary>
    [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="name")]
    [System.Xml.Serialization.SoapAttributeAttribute(AttributeName="name")]
    public string Name {
      get {
        return this._name;
      }
      set {
        this._name = value;
      }
    }
    /// <summary>
    ///  the artist's sort name, e.g. &lt;em&gt;&amp;quot;Beatles, The&amp;quot;&lt;/em&gt; or
    ///  &lt;em&gt;&amp;quot;Springsteen, Bruce&amp;quot;&lt;/em&gt;
    /// </summary>
    [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="sortName")]
    [System.Xml.Serialization.SoapAttributeAttribute(AttributeName="sortName")]
    public string SortName {
      get {
        return this._sortName;
      }
      set {
        this._sortName = value;
      }
    }
    /// <summary>
    ///  the attribution url
    /// </summary>
    [System.Xml.Serialization.XmlElementAttribute(ElementName="url",Namespace="")]
    [System.Xml.Serialization.SoapElementAttribute(ElementName="url")]
    public string Url {
      get {
        return this._url;
      }
      set {
        this._url = value;
      }
    }
  }
}  
namespace Fm.Setlist.Api.Model {

  /// <remarks>
  ///  A Result consisting of a list of artists.
  /// </remarks>
  /// <summary>
  ///  A Result consisting of a list of artists.
  /// </summary>
  [System.SerializableAttribute()]
  [System.Xml.Serialization.XmlTypeAttribute(Namespace="",TypeName="artists")]
  [System.Xml.Serialization.SoapTypeAttribute(TypeName="artists")]
  [System.Xml.Serialization.XmlRootAttribute(Namespace="",ElementName="artists")]
  public partial class Artists : Fm.Setlist.Api.Model.Result {

    private System.Collections.Generic.List<Fm.Setlist.Api.Model.Artist> _list;
    /// <summary>
    ///  result list of artists
    /// </summary>
    [System.Xml.Serialization.XmlElementAttribute(ElementName="artist",Namespace="")]
    [System.Xml.Serialization.SoapElementAttribute(ElementName="artist")]
    public System.Collections.Generic.List<Fm.Setlist.Api.Model.Artist> List {
      get {
        return this._list;
      }
      set {
        this._list = value;
      }
    }
  }
}  
namespace Fm.Setlist.Api.Model {

  /// <remarks>
  ///  A Result consisting of a list of cities.
  /// </remarks>
  /// <summary>
  ///  A Result consisting of a list of cities.
  /// </summary>
  [System.SerializableAttribute()]
  [System.Xml.Serialization.XmlTypeAttribute(Namespace="",TypeName="cities")]
  [System.Xml.Serialization.SoapTypeAttribute(TypeName="cities")]
  [System.Xml.Serialization.XmlRootAttribute(Namespace="",ElementName="cities")]
  public partial class Cities : Fm.Setlist.Api.Model.Result {

    private System.Collections.Generic.List<Fm.Setlist.Api.Model.City> _list;
    /// <summary>
    ///  result list of cities
    /// </summary>
    [System.Xml.Serialization.XmlElementAttribute(ElementName="cities",Namespace="")]
    [System.Xml.Serialization.SoapElementAttribute(ElementName="cities")]
    public System.Collections.Generic.List<Fm.Setlist.Api.Model.City> List {
      get {
        return this._list;
      }
      set {
        this._list = value;
      }
    }
  }
}  
namespace Fm.Setlist.Api.Model {

  /// <remarks>
  ///  This class represents a city where Venues are located. Most of the
  ///  original city data was taken from &lt;a
  ///  href=&quot;http://geonames.org/&quot;&gt;Geonames.org&lt;/a&gt;.
  /// </remarks>
  /// <summary>
  ///  This class represents a city where Venues are located. Most of the
  ///  original city data was taken from &lt;a
  ///  href=&quot;http://geonames.org/&quot;&gt;Geonames.org&lt;/a&gt;.
  /// </summary>
  [System.SerializableAttribute()]
  [System.Xml.Serialization.XmlTypeAttribute(Namespace="",TypeName="city")]
  [System.Xml.Serialization.SoapTypeAttribute(TypeName="city")]
  [System.Xml.Serialization.XmlRootAttribute(Namespace="",ElementName="city")]
  public partial class City {

    private string _id;
    private string _name;
    private string _state;
    private string _stateCode;
    private Fm.Setlist.Api.Model.Coords _coords;
    private Fm.Setlist.Api.Model.Country _country;
    /// <summary>
    ///  unique identifier
    /// </summary>
    [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="id")]
    [System.Xml.Serialization.SoapAttributeAttribute(AttributeName="id")]
    public string Id {
      get {
        return this._id;
      }
      set {
        this._id = value;
      }
    }
    /// <summary>
    ///  the city's name, depending on the language valid values are e.g.
    ///  &lt;em&gt;&amp;quot;M&amp;uuml;chen&amp;quot;&lt;/em&gt; or &lt;em&gt;Munich&lt;/em&gt;
    /// </summary>
    [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="name")]
    [System.Xml.Serialization.SoapAttributeAttribute(AttributeName="name")]
    public string Name {
      get {
        return this._name;
      }
      set {
        this._name = value;
      }
    }
    /// <summary>
    ///  The name of city's state, e.g. &lt;em&gt;&amp;quot;Bavaria&amp;quot;&lt;/em&gt; or
    ///  &lt;em&gt;&amp;quot;Florida&amp;quot;&lt;/em&gt;
    /// </summary>
    [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="state")]
    [System.Xml.Serialization.SoapAttributeAttribute(AttributeName="state")]
    public string State {
      get {
        return this._state;
      }
      set {
        this._state = value;
      }
    }
    /// <summary>
    ///  The code of the city's state. For most countries this two-digit
    ///  numeric code, with which the state can be identified uniquely in
    ///  the specific Country. The code can also be a String for
    ///  other cities. Valid examples are &lt;em&gt;&amp;quot;CA&amp;quot;&lt;/em&gt; or
    ///  &lt;em&gt;&amp;quot;02&amp;quot;&lt;/em&gt;
    ///  
    ///  which in turn get uniquely identifiable when combined with the
    ///  state's country:
    ///  
    ///  &lt;em&gt;&amp;quot;US.CA&amp;quot;&lt;/em&gt; for California, United States or
    ///  &lt;em&gt;&amp;quot;DE.02&amp;quot;&lt;/em&gt; for Bavaria, Germany
    ///  
    ///  For a complete list of available states (that aren't necessarily
    ///  used in this database) is available in &lt;a
    ///  href=&quot;http://download.geonames.org/export/dump/admin1Codes.txt&quot;&gt;a
    ///  textfile on geonames.org&lt;/a&gt;.
    ///  
    ///  Note that this code is only unique combined with the city's
    ///  Country. The code alone is &lt;strong&gt;not&lt;/strong&gt; unique.
    /// </summary>
    [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="stateCode")]
    [System.Xml.Serialization.SoapAttributeAttribute(AttributeName="stateCode")]
    public string StateCode {
      get {
        return this._stateCode;
      }
      set {
        this._stateCode = value;
      }
    }
    /// <summary>
    ///  The city's coordinates. Usually the coordinates of the city centre are
    ///  used.
    /// </summary>
    [System.Xml.Serialization.XmlElementAttribute(ElementName="coords",Namespace="")]
    [System.Xml.Serialization.SoapElementAttribute(ElementName="coords")]
    public Fm.Setlist.Api.Model.Coords Coords {
      get {
        return this._coords;
      }
      set {
        this._coords = value;
      }
    }
    /// <summary>
    ///  The city's country.
    /// </summary>
    [System.Xml.Serialization.XmlElementAttribute(ElementName="country",Namespace="")]
    [System.Xml.Serialization.SoapElementAttribute(ElementName="country")]
    public Fm.Setlist.Api.Model.Country Country {
      get {
        return this._country;
      }
      set {
        this._country = value;
      }
    }
  }
}  
namespace Fm.Setlist.Api.Model {

  /// <remarks>
  ///  Coordinates of a point on the globe. Mostly used for Cities.
  /// </remarks>
  /// <summary>
  ///  Coordinates of a point on the globe. Mostly used for Cities.
  /// </summary>
  [System.SerializableAttribute()]
  [System.Xml.Serialization.XmlTypeAttribute(Namespace="",TypeName="coords")]
  [System.Xml.Serialization.SoapTypeAttribute(TypeName="coords")]
  public partial class Coords {

    private double? _longitude;
    private bool _longitudeSpecified;
    private double? _latitude;
    private bool _latitudeSpecified;
    /// <summary>
    ///  The longitude part of the coordinates.
    /// </summary>
    [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="long")]
    [System.Xml.Serialization.SoapAttributeAttribute(AttributeName="long")]
    public double Longitude {
      get {
        return this._longitude.GetValueOrDefault();
      }
      set {
        this._longitude = value;
        this._longitudeSpecified = true;
      }
    }

    /// <summary>
    ///  Property for the XML serializer indicating whether the "Longitude" property should be included in the output.
    /// </summary>
    [System.Xml.Serialization.XmlIgnoreAttribute]
    [System.Xml.Serialization.SoapIgnoreAttribute]
    [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
    public bool LongitudeSpecified {
      get {
        return this._longitudeSpecified;
      }
      set {
        this._longitudeSpecified = value;
      }
    }

    /// <summary>
    ///  The latitude part of the coordinates.
    /// </summary>
    [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="lat")]
    [System.Xml.Serialization.SoapAttributeAttribute(AttributeName="lat")]
    public double Latitude {
      get {
        return this._latitude.GetValueOrDefault();
      }
      set {
        this._latitude = value;
        this._latitudeSpecified = true;
      }
    }

    /// <summary>
    ///  Property for the XML serializer indicating whether the "Latitude" property should be included in the output.
    /// </summary>
    [System.Xml.Serialization.XmlIgnoreAttribute]
    [System.Xml.Serialization.SoapIgnoreAttribute]
    [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
    public bool LatitudeSpecified {
      get {
        return this._latitudeSpecified;
      }
      set {
        this._latitudeSpecified = value;
      }
    }

  }
}  
namespace Fm.Setlist.Api.Model {

  /// <remarks>
  ///  A Result consisting of a list of countries.
  /// </remarks>
  /// <summary>
  ///  A Result consisting of a list of countries.
  /// </summary>
  [System.SerializableAttribute()]
  [System.Xml.Serialization.XmlTypeAttribute(Namespace="",TypeName="countries")]
  [System.Xml.Serialization.SoapTypeAttribute(TypeName="countries")]
  [System.Xml.Serialization.XmlRootAttribute(Namespace="",ElementName="countries")]
  public partial class Countries : Fm.Setlist.Api.Model.Result {

    private System.Collections.Generic.List<Fm.Setlist.Api.Model.Country> _list;
    /// <summary>
    ///  result list of countries
    /// </summary>
    [System.Xml.Serialization.XmlElementAttribute(ElementName="country",Namespace="")]
    [System.Xml.Serialization.SoapElementAttribute(ElementName="country")]
    public System.Collections.Generic.List<Fm.Setlist.Api.Model.Country> List {
      get {
        return this._list;
      }
      set {
        this._list = value;
      }
    }
  }
}  
namespace Fm.Setlist.Api.Model {

  /// <remarks>
  ///  This class represents a country on earth.
  /// </remarks>
  /// <summary>
  ///  This class represents a country on earth.
  /// </summary>
  [System.SerializableAttribute()]
  [System.Xml.Serialization.XmlTypeAttribute(Namespace="",TypeName="country")]
  [System.Xml.Serialization.SoapTypeAttribute(TypeName="country")]
  [System.Xml.Serialization.XmlRootAttribute(Namespace="",ElementName="country")]
  public partial class Country {

    private string _name;
    private string _code;
    /// <summary>
    ///  The country's name. Can be a localized name - e.g.
    ///  &lt;em&gt;&amp;quot;Austria&amp;quot;&lt;/em&gt; or
    ///  &lt;em&gt;&amp;quot;&amp;Ouml;sterreich&amp;quot;&lt;/em&gt; for Austria if the German
    ///  name was requested.
    /// </summary>
    [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="name")]
    [System.Xml.Serialization.SoapAttributeAttribute(AttributeName="name")]
    public string Name {
      get {
        return this._name;
      }
      set {
        this._name = value;
      }
    }
    /// <summary>
    ///  The country's &lt;a
    ///  href=&quot;http://www.iso.org/iso/english_country_names_and_code_elements&quot;
    ///  &gt;ISO code&lt;/a&gt;. E.g. &lt;em&gt;&amp;quot;ie&amp;quot;&lt;/em&gt; for Ireland
    /// </summary>
    [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="code")]
    [System.Xml.Serialization.SoapAttributeAttribute(AttributeName="code")]
    public string Code {
      get {
        return this._code;
      }
      set {
        this._code = value;
      }
    }
  }
}  
namespace Fm.Setlist.Api.Model {

  /// <remarks>
  ///  &lt;p&gt;
  ///  If a request returns a list of items they're always wrapped into a Result. As
  ///  there is a maximum amount of items to be returned at once a Result consists
  ///  of the total amount of items (total), how many items per page you get
  ///  (itemsPerPage), the current page (page) and the current list of items.
  ///  &lt;/p&gt;
  ///  
  ///  &lt;p&gt;
  ///  E.g. if there are 35 items, itemsPerPage is 10 and the current page is 2,
  ///  then items 11 to 20 are in the list.
  ///  &lt;/p&gt;
  /// </remarks>
  /// <summary>
  ///  &lt;p&gt;
  ///  If a request returns a list of items they're always wrapped into a Result. As
  ///  there is a maximum amount of items to be returned at once a Result consists
  ///  of the total amount of items (total), how many items per page you get
  ///  (itemsPerPage), the current page (page) and the current list of items.
  ///  &lt;/p&gt;
  ///  
  ///  &lt;p&gt;
  ///  E.g. if there are 35 items, itemsPerPage is 10 and the current page is 2,
  ///  then items 11 to 20 are in the list.
  ///  &lt;/p&gt;
  /// </summary>
  [System.SerializableAttribute()]
  [System.Xml.Serialization.XmlTypeAttribute(Namespace="",TypeName="result")]
  [System.Xml.Serialization.SoapTypeAttribute(TypeName="result")]
  public abstract partial class Result {

    private int _total;
    private int _page;
    private int _itemsPerPage;
    /// <summary>
    ///  the total amount of items matching the query
    /// </summary>
    [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="total")]
    [System.Xml.Serialization.SoapAttributeAttribute(AttributeName="total")]
    public int Total {
      get {
        return this._total;
      }
      set {
        this._total = value;
      }
    }
    /// <summary>
    ///  the current page
    /// </summary>
    [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="page")]
    [System.Xml.Serialization.SoapAttributeAttribute(AttributeName="page")]
    public int Page {
      get {
        return this._page;
      }
      set {
        this._page = value;
      }
    }
    /// <summary>
    ///  the amount of items you get per page
    /// </summary>
    [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="itemsPerPage")]
    [System.Xml.Serialization.SoapAttributeAttribute(AttributeName="itemsPerPage")]
    public int ItemsPerPage {
      get {
        return this._itemsPerPage;
      }
      set {
        this._itemsPerPage = value;
      }
    }
  }
}  
namespace Fm.Setlist.Api.Model {

  /// <remarks>
  ///  A setlist consists of different (at least one) sets. Sets can either be sets
  ///  as defined in the &lt;a href=&quot;http://www.setlist.fm/guidelines&quot;&gt;Guidelines&lt;/a&gt;
  ///  or encores.
  /// </remarks>
  /// <summary>
  ///  A setlist consists of different (at least one) sets. Sets can either be sets
  ///  as defined in the &lt;a href=&quot;http://www.setlist.fm/guidelines&quot;&gt;Guidelines&lt;/a&gt;
  ///  or encores.
  /// </summary>
  [System.SerializableAttribute()]
  [System.Xml.Serialization.XmlTypeAttribute(Namespace="",TypeName="set")]
  [System.Xml.Serialization.SoapTypeAttribute(TypeName="set")]
  public partial class Set {

    private int? _encore;
    private bool _encoreSpecified;
    private string _name;
    private System.Collections.Generic.List<Fm.Setlist.Api.Model.Song> _songs;
    /// <summary>
    ///  if the set is an encore, this is the number of the encore,
    ///  starting with 1 for the first encore, 2 for the second and so on.
    /// </summary>
    [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="encore")]
    [System.Xml.Serialization.SoapAttributeAttribute(AttributeName="encore")]
    public int Encore {
      get {
        return this._encore.GetValueOrDefault();
      }
      set {
        this._encore = value;
        this._encoreSpecified = true;
      }
    }

    /// <summary>
    ///  Property for the XML serializer indicating whether the "Encore" property should be included in the output.
    /// </summary>
    [System.Xml.Serialization.XmlIgnoreAttribute]
    [System.Xml.Serialization.SoapIgnoreAttribute]
    [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
    public bool EncoreSpecified {
      get {
        return this._encoreSpecified;
      }
      set {
        this._encoreSpecified = value;
      }
    }

    /// <summary>
    ///  the description/name of the set. E.g.
    ///  &lt;em&gt;&amp;quot;Acoustic set&amp;quot;&lt;/em&gt; or
    ///  &lt;em&gt;&amp;quot;Paul McCartney solo&amp;quot;&lt;/em&gt;
    /// </summary>
    [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="name")]
    [System.Xml.Serialization.SoapAttributeAttribute(AttributeName="name")]
    public string Name {
      get {
        return this._name;
      }
      set {
        this._name = value;
      }
    }
    /// <summary>
    ///  this set's songs
    /// </summary>
    [System.Xml.Serialization.XmlElementAttribute(ElementName="song",Namespace="")]
    [System.Xml.Serialization.SoapElementAttribute(ElementName="song")]
    public System.Collections.Generic.List<Fm.Setlist.Api.Model.Song> Songs {
      get {
        return this._songs;
      }
      set {
        this._songs = value;
      }
    }
  }
}  
namespace Fm.Setlist.Api.Model {

  /// <remarks>
  ///  Setlists, that's what it's all about. So if you're trying to use this API
  ///  without knowing what a setlist is then you're kinda wrong on this page ;-).
  ///  
  ///  A setlist can be distinguished from other setlists by its unique id. But as
  ///  &lt;a href=&quot;http://www.setlist.fm/&quot;&gt;setlist.fm&lt;/a&gt; works the wiki way, there can
  ///  be different versions of one setlist (each time a user updates a setlist a
  ///  new version gets created). These different versions have a unique id on its
  ///  own. So setlists can have the same id although they differ as far as the
  ///  content is concerned - thus the best way to check if two setlists are the
  ///  same is to compare their versionIds.
  /// </remarks>
  /// <summary>
  ///  Setlists, that's what it's all about. So if you're trying to use this API
  ///  without knowing what a setlist is then you're kinda wrong on this page ;-).
  ///  
  ///  A setlist can be distinguished from other setlists by its unique id. But as
  ///  &lt;a href=&quot;http://www.setlist.fm/&quot;&gt;setlist.fm&lt;/a&gt; works the wiki way, there can
  ///  be different versions of one setlist (each time a user updates a setlist a
  ///  new version gets created). These different versions have a unique id on its
  ///  own. So setlists can have the same id although they differ as far as the
  ///  content is concerned - thus the best way to check if two setlists are the
  ///  same is to compare their versionIds.
  /// </summary>
  [System.SerializableAttribute()]
  [System.Xml.Serialization.XmlTypeAttribute(Namespace="",TypeName="setlist")]
  [System.Xml.Serialization.SoapTypeAttribute(TypeName="setlist")]
  [System.Xml.Serialization.XmlRootAttribute(Namespace="",ElementName="setlist")]
  public partial class Setlist {

    private string _id;
    private string _eventDate;
    private string _lastUpdated;
    private string _versionId;
    private string _tour;
    private int? _lastFmEventId;
    private bool _lastFmEventIdSpecified;
    private Fm.Setlist.Api.Model.Artist _artist;
    private Fm.Setlist.Api.Model.Venue _venue;
    private System.Collections.Generic.List<Fm.Setlist.Api.Model.Set> _sets;
    private string _info;
    private string _url;
    /// <summary>
    ///  unique identifier
    /// </summary>
    [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="id")]
    [System.Xml.Serialization.SoapAttributeAttribute(AttributeName="id")]
    public string Id {
      get {
        return this._id;
      }
      set {
        this._id = value;
      }
    }
    /// <summary>
    ///  date of the concert in the format &amp;quot;dd-MM-yyyy&amp;quot;
    /// </summary>
    [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="eventDate")]
    [System.Xml.Serialization.SoapAttributeAttribute(AttributeName="eventDate")]
    public string EventDate {
      get {
        return this._eventDate;
      }
      set {
        this._eventDate = value;
      }
    }
    /// <summary>
    ///  date, time and time zone of the last update to this setlist in
    ///  the format &amp;quot;yyyy-MM-dd'T'HH:mm:ss.SSSZZZZZ&amp;quot;
    /// </summary>
    [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="lastUpdated")]
    [System.Xml.Serialization.SoapAttributeAttribute(AttributeName="lastUpdated")]
    public string LastUpdated {
      get {
        return this._lastUpdated;
      }
      set {
        this._lastUpdated = value;
      }
    }
    /// <summary>
    ///  unique identifier of the version
    /// </summary>
    [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="versionId")]
    [System.Xml.Serialization.SoapAttributeAttribute(AttributeName="versionId")]
    public string VersionId {
      get {
        return this._versionId;
      }
      set {
        this._versionId = value;
      }
    }
    /// <summary>
    ///  the setlist's tour
    /// </summary>
    [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="tour")]
    [System.Xml.Serialization.SoapAttributeAttribute(AttributeName="tour")]
    public string Tour {
      get {
        return this._tour;
      }
      set {
        this._tour = value;
      }
    }
    /// <summary>
    ///  the id this event has on &lt;a href=&quot;http://last.fm/&quot;&gt;last.fm&lt;/a&gt;
    /// </summary>
    [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="lastFmEventId")]
    [System.Xml.Serialization.SoapAttributeAttribute(AttributeName="lastFmEventId")]
    public int LastFmEventId {
      get {
        return this._lastFmEventId.GetValueOrDefault();
      }
      set {
        this._lastFmEventId = value;
        this._lastFmEventIdSpecified = true;
      }
    }

    /// <summary>
    ///  Property for the XML serializer indicating whether the "LastFmEventId" property should be included in the output.
    /// </summary>
    [System.Xml.Serialization.XmlIgnoreAttribute]
    [System.Xml.Serialization.SoapIgnoreAttribute]
    [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
    public bool LastFmEventIdSpecified {
      get {
        return this._lastFmEventIdSpecified;
      }
      set {
        this._lastFmEventIdSpecified = value;
      }
    }

    /// <summary>
    ///  the setlist's artist
    /// </summary>
    [System.Xml.Serialization.XmlElementAttribute(ElementName="artist",Namespace="")]
    [System.Xml.Serialization.SoapElementAttribute(ElementName="artist")]
    public Fm.Setlist.Api.Model.Artist Artist {
      get {
        return this._artist;
      }
      set {
        this._artist = value;
      }
    }
    /// <summary>
    ///  the setlist's venue
    /// </summary>
    [System.Xml.Serialization.XmlElementAttribute(ElementName="venue",Namespace="")]
    [System.Xml.Serialization.SoapElementAttribute(ElementName="venue")]
    public Fm.Setlist.Api.Model.Venue Venue {
      get {
        return this._venue;
      }
      set {
        this._venue = value;
      }
    }
    /// <summary>
    ///  all sets of this setlist
    /// </summary>
    [System.Xml.Serialization.XmlArrayAttribute(ElementName="sets",Namespace="")]
    [System.Xml.Serialization.XmlArrayItemAttribute(ElementName="set",Namespace="")]
    [System.Xml.Serialization.SoapElementAttribute(ElementName="set")]
    public System.Collections.Generic.List<Fm.Setlist.Api.Model.Set> Sets {
      get {
        return this._sets;
      }
      set {
        this._sets = value;
      }
    }
    /// <summary>
    ///  additional information on the concert - see the &lt;a
    ///  href=&quot;http://www.setlist.fm/guidelines&quot;&gt;setlist.fm guidelines&lt;/a&gt;
    ///  for a complete list of allowed content.
    /// </summary>
    [System.Xml.Serialization.XmlElementAttribute(ElementName="info",Namespace="")]
    [System.Xml.Serialization.SoapElementAttribute(ElementName="info")]
    public string Info {
      get {
        return this._info;
      }
      set {
        this._info = value;
      }
    }
    /// <summary>
    ///  the attribution url to which you have to link to wherever you use
    ///  data from this setlist in your application
    /// </summary>
    [System.Xml.Serialization.XmlElementAttribute(ElementName="url",Namespace="")]
    [System.Xml.Serialization.SoapElementAttribute(ElementName="url")]
    public string Url {
      get {
        return this._url;
      }
      set {
        this._url = value;
      }
    }
  }
}  
namespace Fm.Setlist.Api.Model {

  /// <remarks>
  ///  A Result consisting of a list of setlists.
  /// </remarks>
  /// <summary>
  ///  A Result consisting of a list of setlists.
  /// </summary>
  [System.SerializableAttribute()]
  [System.Xml.Serialization.XmlTypeAttribute(Namespace="",TypeName="setlists")]
  [System.Xml.Serialization.SoapTypeAttribute(TypeName="setlists")]
  [System.Xml.Serialization.XmlRootAttribute(Namespace="",ElementName="setlists")]
  public partial class Setlists : Fm.Setlist.Api.Model.Result {

    private System.Collections.Generic.List<Fm.Setlist.Api.Model.Setlist> _list;
    /// <summary>
    ///  result list of setlists
    /// </summary>
    [System.Xml.Serialization.XmlElementAttribute(ElementName="setlist",Namespace="")]
    [System.Xml.Serialization.SoapElementAttribute(ElementName="setlist")]
    public System.Collections.Generic.List<Fm.Setlist.Api.Model.Setlist> List {
      get {
        return this._list;
      }
      set {
        this._list = value;
      }
    }
  }
}  
namespace Fm.Setlist.Api.Model {

  /// <remarks>
  ///  This class represents a song that is part of a Set.
  /// </remarks>
  /// <summary>
  ///  This class represents a song that is part of a Set.
  /// </summary>
  [System.SerializableAttribute()]
  [System.Xml.Serialization.XmlTypeAttribute(Namespace="",TypeName="song")]
  [System.Xml.Serialization.SoapTypeAttribute(TypeName="song")]
  [System.Xml.Serialization.XmlRootAttribute(Namespace="",ElementName="song")]
  public partial class Song {

    private string _name;
    private bool? _tape;
    private bool _tapeSpecified;
    private Fm.Setlist.Api.Model.Artist _with;
    private Fm.Setlist.Api.Model.Artist _cover;
    private string _info;
    /// <summary>
    ///  The name of the song. E.g. &lt;em&gt;Yesterday&lt;/em&gt; or
    ///  &lt;em&gt;&amp;quot;Wish You Were Here&amp;quot;&lt;/em&gt;
    /// </summary>
    [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="name")]
    [System.Xml.Serialization.SoapAttributeAttribute(AttributeName="name")]
    public string Name {
      get {
        return this._name;
      }
      set {
        this._name = value;
      }
    }
    /// <summary>
    ///  The song came from tape rather than being performed live. See the &lt;a
    ///  href=&quot;http://www.setlist.fm/guidelines#tape-songs&quot;&gt;tape section of the
    ///  guidelines&lt;/a&gt; for valid usage.
    /// </summary>
    [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="tape")]
    [System.Xml.Serialization.SoapAttributeAttribute(AttributeName="tape")]
    public bool Tape {
      get {
        return this._tape.GetValueOrDefault();
      }
      set {
        this._tape = value;
        this._tapeSpecified = true;
      }
    }

    /// <summary>
    ///  Property for the XML serializer indicating whether the "Tape" property should be included in the output.
    /// </summary>
    [System.Xml.Serialization.XmlIgnoreAttribute]
    [System.Xml.Serialization.SoapIgnoreAttribute]
    [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
    public bool TapeSpecified {
      get {
        return this._tapeSpecified;
      }
      set {
        this._tapeSpecified = value;
      }
    }

    /// <summary>
    ///  A different Artist than the performing one that joined the stage
    ///  for this song.
    /// </summary>
    [System.Xml.Serialization.XmlElementAttribute(ElementName="with",Namespace="")]
    [System.Xml.Serialization.SoapElementAttribute(ElementName="with")]
    public Fm.Setlist.Api.Model.Artist With {
      get {
        return this._with;
      }
      set {
        this._with = value;
      }
    }
    /// <summary>
    ///  The original Artist of this song, if different to the performing
    ///  artist.
    /// </summary>
    [System.Xml.Serialization.XmlElementAttribute(ElementName="cover",Namespace="")]
    [System.Xml.Serialization.SoapElementAttribute(ElementName="cover")]
    public Fm.Setlist.Api.Model.Artist Cover {
      get {
        return this._cover;
      }
      set {
        this._cover = value;
      }
    }
    /// <summary>
    ///  Special incidents or additional information about the way the song was
    ///  performed at this specific concert. See the &lt;a
    ///  href=&quot;http://www.setlist.fm/guidelines&quot;&gt;setlist.fm guidelines&lt;/a&gt; for a
    ///  complete list of allowed content.
    /// </summary>
    [System.Xml.Serialization.XmlElementAttribute(ElementName="info",Namespace="")]
    [System.Xml.Serialization.SoapElementAttribute(ElementName="info")]
    public string Info {
      get {
        return this._info;
      }
      set {
        this._info = value;
      }
    }
  }
}  
namespace Fm.Setlist.Api.Model {

  /// <remarks>
  ///  This class represents a user.
  /// </remarks>
  /// <summary>
  ///  This class represents a user.
  /// </summary>
  [System.SerializableAttribute()]
  [System.Xml.Serialization.XmlTypeAttribute(Namespace="",TypeName="user")]
  [System.Xml.Serialization.SoapTypeAttribute(TypeName="user")]
  [System.Xml.Serialization.XmlRootAttribute(Namespace="",ElementName="user")]
  public partial class User {

    private string _flickr;
    private string _twitter;
    private string _website;
    private string _userId;
    private string _lastFm;
    private string _mySpace;
    private string _fullname;
    private string _about;
    private string _url;
    /// <summary>
    ///  (no documentation provided)
    /// </summary>
    [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="flickr")]
    [System.Xml.Serialization.SoapAttributeAttribute(AttributeName="flickr")]
    public string Flickr {
      get {
        return this._flickr;
      }
      set {
        this._flickr = value;
      }
    }
    /// <summary>
    ///  (no documentation provided)
    /// </summary>
    [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="twitter")]
    [System.Xml.Serialization.SoapAttributeAttribute(AttributeName="twitter")]
    public string Twitter {
      get {
        return this._twitter;
      }
      set {
        this._twitter = value;
      }
    }
    /// <summary>
    ///  (no documentation provided)
    /// </summary>
    [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="website")]
    [System.Xml.Serialization.SoapAttributeAttribute(AttributeName="website")]
    public string Website {
      get {
        return this._website;
      }
      set {
        this._website = value;
      }
    }
    /// <summary>
    ///  (no documentation provided)
    /// </summary>
    [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="userId")]
    [System.Xml.Serialization.SoapAttributeAttribute(AttributeName="userId")]
    public string UserId {
      get {
        return this._userId;
      }
      set {
        this._userId = value;
      }
    }
    /// <summary>
    ///  (no documentation provided)
    /// </summary>
    [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="lastFm")]
    [System.Xml.Serialization.SoapAttributeAttribute(AttributeName="lastFm")]
    public string LastFm {
      get {
        return this._lastFm;
      }
      set {
        this._lastFm = value;
      }
    }
    /// <summary>
    ///  (no documentation provided)
    /// </summary>
    [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="mySpace")]
    [System.Xml.Serialization.SoapAttributeAttribute(AttributeName="mySpace")]
    public string MySpace {
      get {
        return this._mySpace;
      }
      set {
        this._mySpace = value;
      }
    }
    /// <summary>
    ///  (no documentation provided)
    /// </summary>
    [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="fullname")]
    [System.Xml.Serialization.SoapAttributeAttribute(AttributeName="fullname")]
    public string Fullname {
      get {
        return this._fullname;
      }
      set {
        this._fullname = value;
      }
    }
    /// <summary>
    ///  (no documentation provided)
    /// </summary>
    [System.Xml.Serialization.XmlElementAttribute(ElementName="about",Namespace="")]
    [System.Xml.Serialization.SoapElementAttribute(ElementName="about")]
    public string About {
      get {
        return this._about;
      }
      set {
        this._about = value;
      }
    }
    /// <summary>
    ///  (no documentation provided)
    /// </summary>
    [System.Xml.Serialization.XmlElementAttribute(ElementName="url",Namespace="")]
    [System.Xml.Serialization.SoapElementAttribute(ElementName="url")]
    public string Url {
      get {
        return this._url;
      }
      set {
        this._url = value;
      }
    }
  }
}  
namespace Fm.Setlist.Api.Model {

  /// <remarks>
  ///  Venues are places where concerts take place. They usually consist of a venue
  ///  name and a city - but there are also some venues that do not have a city
  ///  attached yet. In such a case, the city simply isn't set and the city and
  ///  country may (but do not have to) be in the name.
  /// </remarks>
  /// <summary>
  ///  Venues are places where concerts take place. They usually consist of a venue
  ///  name and a city - but there are also some venues that do not have a city
  ///  attached yet. In such a case, the city simply isn't set and the city and
  ///  country may (but do not have to) be in the name.
  /// </summary>
  [System.SerializableAttribute()]
  [System.Xml.Serialization.XmlTypeAttribute(Namespace="",TypeName="venue")]
  [System.Xml.Serialization.SoapTypeAttribute(TypeName="venue")]
  [System.Xml.Serialization.XmlRootAttribute(Namespace="",ElementName="venue")]
  public partial class Venue {

    private string _id;
    private string _name;
    private Fm.Setlist.Api.Model.City _city;
    private string _url;
    /// <summary>
    ///  unique identifier
    /// </summary>
    [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="id")]
    [System.Xml.Serialization.SoapAttributeAttribute(AttributeName="id")]
    public string Id {
      get {
        return this._id;
      }
      set {
        this._id = value;
      }
    }
    /// <summary>
    ///  the name of the venue, usually without city and country. E.g.
    ///  &lt;em&gt;&amp;quot;Madison Square Garden&amp;quot;&lt;/em&gt; or
    ///  &lt;em&gt;&amp;quot;Royal Albert Hall&amp;quot;&lt;/em&gt;
    /// </summary>
    [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="name")]
    [System.Xml.Serialization.SoapAttributeAttribute(AttributeName="name")]
    public string Name {
      get {
        return this._name;
      }
      set {
        this._name = value;
      }
    }
    /// <summary>
    ///  the city in which the venue is located
    /// </summary>
    [System.Xml.Serialization.XmlElementAttribute(ElementName="city",Namespace="")]
    [System.Xml.Serialization.SoapElementAttribute(ElementName="city")]
    public Fm.Setlist.Api.Model.City City {
      get {
        return this._city;
      }
      set {
        this._city = value;
      }
    }
    /// <summary>
    ///  the attribution url
    /// </summary>
    [System.Xml.Serialization.XmlElementAttribute(ElementName="url",Namespace="")]
    [System.Xml.Serialization.SoapElementAttribute(ElementName="url")]
    public string Url {
      get {
        return this._url;
      }
      set {
        this._url = value;
      }
    }
  }
}  
namespace Fm.Setlist.Api.Model {

  /// <remarks>
  ///  A Result consisting of a list of venues.
  /// </remarks>
  /// <summary>
  ///  A Result consisting of a list of venues.
  /// </summary>
  [System.SerializableAttribute()]
  [System.Xml.Serialization.XmlTypeAttribute(Namespace="",TypeName="venues")]
  [System.Xml.Serialization.SoapTypeAttribute(TypeName="venues")]
  [System.Xml.Serialization.XmlRootAttribute(Namespace="",ElementName="venues")]
  public partial class Venues : Fm.Setlist.Api.Model.Result {

    private System.Collections.Generic.List<Fm.Setlist.Api.Model.Venue> _list;
    /// <summary>
    ///  result list of venues
    /// </summary>
    [System.Xml.Serialization.XmlElementAttribute(ElementName="venue",Namespace="")]
    [System.Xml.Serialization.SoapElementAttribute(ElementName="venue")]
    public System.Collections.Generic.List<Fm.Setlist.Api.Model.Venue> List {
      get {
        return this._list;
      }
      set {
        this._list = value;
      }
    }
  }
}  
